#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;
	
	location /redirect_me {
		return 301 https://google.com;
	}
}" > /etc/nginx/sites_available/default
service nginx start
