#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;
	
	location /redirect_me {
		return 301 https://google.com;
	}

	error_page 404/404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites_available/default
service nginx start
