#!/usr/bin/env bash
# Install and configure HAproxy in a load balancing server.

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
sudo echo "ENABLED=1" >> /etc/default/haproxy 
sudo echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 29515-web-01 3.235.66.4:80 check\n\tserver 29515-web-02 3.235.223.210:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
