#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
sudo echo "ENABLED=1" >> /etc/default/haproxy 
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 11515-web-01 3.227.252.206:80 check\n\tserver 11515-web-02 3.236.140.250:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
