#!/usr/bin/env bash
# Install and configure HAproxy in a load balancing server.

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
sudo echo "
\nfrontend front
        bind *:80
        mode http
        default_backend back

backend back
        balance roundrobin
        server 29515-web-01 3.235.66.4 check
        server 29515-web-02 3.235.223.210 check
" >> /etc/haproxy/haproxy.cfg
