#!/usr/bin/env bash
#  This script creates a file containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file and terminates itself when receiving a
#+ SIGQUIT or SIGTERM signal

trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

while true
do
	echo "To infinity and beyond"
	sleep 2
done
