#!/usr/bin/env bash
#  This script displays the username, user id and home directory path
#+ for the files in /etc/passwd.

dirn="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f 1,3,6
done < "$dirn"
