#!/usr/bin/env bash
#  This script displays numbers from 1 to 20 and
#+ displays 4 and then bad luck from China for the 4th loop iteration
#+ displays 9 and then bad luck from Japan for the 9th loop iteration
#+ displays 17 and then bad luck from Italy for the 17th loop iteration

z=1
while [ $z -le 20 ]
do
	case $z in
		4)
			echo -e "$z\nbad luck from China"
			;;
		9)
			echo -e "$z\nbad luck from Japan"
			;;
		17)
			echo -e "$z\nbad luck from Italy"
			;;
		*)
			echo "$z"
			;;
	esac
	(( z++ ))
done
